title: Information Wanted: Boston Pilot Newspaper
description: This project aims to analyze information regarding missing Irish immigrants from the Boston Pilot Newspaper. <br />
The existing information spans the course of over 100 years, from October 1921 to October 1931.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CHANGELOG.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - LICENSE
  - PULL_REQUEST_TEMPLATE.md
  - README.md
theme: jekyll-theme-minimal
source: ./pages
collections_dir: ./pages
includes_dir: _includes
